### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
### Ingresses 
{{- $ingresses := include "ingresses" . | fromYaml }}
###
{{- range $k, $v := $ingresses.ingresses -}}
{{ if and ($v.secret.create) ($basic.basic.createSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.secret.name }}
  {{- with $annotationsLabels.common}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ $.Files.Get $v.tls.tlsCrtFile | b64enc }}
  tls.key: |
    {{ $.Files.Get $v.tls.tlsKeyFile | b64enc }}
---    
{{- end }}
{{- end }}