### Basic, Annotations
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
### StorageClass
{{- $storageClass:= include "storageClass" . | fromYaml }}
###
{{- if .Values.persistentVolume.persistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-persistent-volume-claim
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with $annotationsLabels.common.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with $.Values.persistentVolume.persistentVolumeClaim.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $annotationsLabels.common.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with $.Values.persistentVolume.persistentVolumeClaim.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  - {{ $storageClass.storageClass.persistentVolumeClaimAccessMode }}
  resources:
    requests:
      storage: {{ $storageClass.storageClass.storage }} 
  storageClassName: {{ $storageClass.storageClass.metadata.name }} 
{{- end }}
