### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
### Secret
{{- $secret := include "secret" . | fromYaml }}
###
{{- if $basic.basic.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: edm-applications-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with $annotationsLabels.common.annotations}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $annotationsLabels.common.labels}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- with $secret }}
{{ toYaml . | nindent 0 }}
{{- end }}
type: Opaque
{{- end }}
---