### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
###  
{{- if $basic.basic.customHelm }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: nuveen-golden-source-secrets-template
data:
  datasource.properties: |
    SchemaPassword_GC=%ser_gs_gc_app%
    SchemaPassword_VDDB=%ser_gs_vd_app%
    SchemaPassword_AUDIT=%ser_gs_ad_app%
    SchemaPassword_INSTREP=%ser_gs_ir%
    SchemaPassword_KEYCLOAK=%ser_gs_kc_app%
    SchemaPassword_JOBSCHEDULER=%ser_gs_js_app%
    SchemaPassword_INSIGHT=%ser_gs_is_app%
    DatabaseOwner_Password=%ser_db_admin%
    Service_Account_Password=%ser_svc_admin%
    KEYCLOAK_ADMIN_PASSWORD=%ser_kc_admin%
    Certificate_identityKeyStorePassphrase=%cert_identity_pwd%
    Certificate_trustKeyStorePassphrase=%cert_trust_pwd%
    GEMSchemaOwnerPassword_AUDIT=%ser_gs_ad%
    GEMSchemaOwnerPassword_GC=%ser_gs_gc%
    GEMSchemaOwnerPassword_INSIGHT=%ser_gs_is%
    GEMSchemaOwnerPassword_INSTREP=%ser_gs_ir%
    GEMSchemaOwnerPassword_JOBSCHEDULER=%ser_gs_js%
    GEMSchemaOwnerPassword_KEYCLOAK=%ser_gs_kc%
    GEMSchemaOwnerPassword_VDDB=%ser_gs_vd%
    GEMSchemaUserPassword_AUDIT=%ser_gs_ad_app%
    GEMSchemaUserPassword_INSTREP=%ser_gs_ir_app%
    GEMSchemaUserPassword_JOBSCHEDULER=%ser_gs_js_app%
    GEMSchemaUserPassword_KEYCLOAK=%ser_gs_kc_app%
    GEMSchemaUserPassword_VDDB=%ser_gs_vd_app%
    GEMSchemaUserPassword_GC=%ser_gs_gc_app%
    GEMSchemaUserPassword_INSIGHT=%ser_gs_is_app%
{{- end }}
