### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
{{- $annotationsLabelsService := include "annotationsLabelsService" . | fromYaml }}
### Applications
{{- $applications := include "applications" . | fromYaml }}
### Checksum
{{- $checkSum := include "checkSum" . | fromYaml }}
###
{{- range $k, $v := $applications.applications -}}
{{- if eq "EDMA" $k }}
apiVersion: {{ $basic.basic.cloud.hpaApiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: selenium-chrome-node
  annotations:
    {{- with $annotationsLabels.common.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $annotationsLabels.common.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selenium-chrome-node
  minReplicas: {{ $.Values.selenium.node.resources.hpa.minReplicas }}
  maxReplicas: {{ $.Values.selenium.node.resources.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.selenium.node.resources.hpa.averageUtilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ $.Values.selenium.node.resources.hpa.scaleUpStabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: 1
        periodSeconds: {{ $.Values.selenium.node.resources.hpa.scaleUpPeriodSeconds }}
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: {{ $.Values.selenium.node.resources.hpa.scaleDownStabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: 1
        periodSeconds: {{ $.Values.selenium.node.resources.hpa.scaleDownPeriodSeconds }}
      selectPolicy: Min
---
{{- end }}
{{- end }}

