### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabelsIngressOrchestrator := include "annotationsLabelsIngressOrchestrator" . | fromYaml }}
### Ingresses
{{- $ingresses := include "ingresses" . | fromYaml }}
###
{{- range $k, $v := $ingresses.ingresses -}}
{{ if (eq $v.type "Orchestrator") }}
{{ if $v.tcpConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $v.tcpConfigMap.name }}
  {{- with $annotationsLabelsIngressOrchestrator.orchestrator}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
data:
  {{ $v.port }}: "{{ $.Release.Namespace }}/{{ lower $k }}:{{ $v.port }}"  
---
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $v.name }}
  annotations:
    # Include orchestrator annotations
    {{- with $v.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $annotationsLabelsIngressOrchestrator.orchestrator.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $v.spec}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- if $basic.basic.cloud.ingressTls }}
  tls:
  - hosts:
    - {{ $v.host }}
    secretName: {{ $v.secret.name }}
  {{- end }}  
  defaultBackend:
    service:
      name: {{ $k }}
      port:
        number: {{ $v.port }}
  {{- if $basic.basic.cloud.ingressTlsHost }}        
  rules:
  - http:
    host: {{ $v.host }}
  {{- end }}    
---
{{- end }}
{{- end }}
