### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- if $basic.basic.externalDns }}
{{- if eq "azure" $basic.basic.cloud.option }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-configmap
data:
  azure.json: |-
{{ .Files.Get "protected/Azure/azure.json" | indent 4}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      {{- with $basic.basic.cluster.node }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ $basic.basic.environment }}-external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.6
        args:
        - --log-format=text
        - --source=service
        - --source=ingress
        - --provider=azure
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=noop
        - --domain-filter={{ $.Values.ingresses.lb.hostedZoneName }}
        - --azure-config-file=/etc/edm/secret/protected/Azure/azure.json
        #- --txt-owner-id={{ $.Values.ingresses.lb.hostedZoneId }}
        volumeMounts:
          - name: external-dns-configmap 
            mountPath: /etc/edm/secret/protected/Azure
      volumes:
        - name: external-dns-configmap
          configMap:
            name: external-dns-configmap
{{- end }}    
{{- end }}