elasticsearch:
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  clusterName: "elasticsearch"
  extraEnvs:
  - name: "ELASTIC_PASSWORD"
    valueFrom:
      secretKeyRef:
        key: "Elasticsearch_password"
        name: "edm-applications-secret"
  - name: "ELASTIC_USERNAME"
    valueFrom:
      secretKeyRef:
        key: "Elasticsearch_user"
        name: "edm-applications-secret"
  minimumMasterNodes: "1"
  nodeGroup: "master"
  nodeSelector:
    node_group_name: "edmcoba-node"
  replicas: 0
  resources:
    limits:
      cpu: 2
      memory: "4Gi"
    requests:
      cpu: 0.1
      memory: "100Mi"
  roles:
    data: "true"
    ingest: "true"
    master: "true"
  volumeClaimTemplate:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "50Gi"
    storageClassName: "edmcoba-storage-class"
