### StorageClass
{{- $storageClass:= include "storageClass" . | fromYaml }}
###
{{- if .Values.persistentVolume.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  {{- with $storageClass.storageClass.metadata }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
{{- with $storageClass.storageClass.configurations }}
{{ toYaml .}}
{{- end }}
{{- end }}
