### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
{{- $annotationsLabelsService := include "annotationsLabelsService" . | fromYaml }}
### Applications
{{- $applications := include "applications" . | fromYaml }}
### Ingresses
{{- $ingresses := include "ingresses" . | fromYaml }}
### Init container
{{- $initContainer := include "initContainer" . | fromYaml }}
### Volume Mounts
{{- $volumeMounts := include "volumeMounts" . | fromYaml }}
### Volumes
{{- $volumes := include "volumes" . | fromYaml }}
### Checksum
{{- $checkSum := include "checkSum" . | fromYaml }}
### Custom
{{- $custom := include "custom" . | fromYaml }}
###
{{- if $basic.basic.processApplications }}
###
{{- range $k, $v := $applications.applications -}}
{{- if eq "Cloudbeaver" $k }}
apiVersion: v1
kind: Service
metadata:
  name: {{ lower $k }}
  annotations:
    {{- with $annotationsLabelsService.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    
    ### Openshift
    {{- if eq $.Values.common.cloud "openshift" }}
    {{- if eq $.Values.ingresses.ingress.ui.ingressClassName "openshift-default" }}
    service.beta.openshift.io/serving-cert-secret-name: {{ printf "edm-openshift-%s" (lower $k) }}
    {{- end }}
    {{- end }}
  labels:
    cluster: {{ lower $k }}
    app: {{ lower $k }}
    {{- with $annotationsLabels.common.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    cluster: {{ lower $k }}
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ lower $k }}
  annotations:
    {{- with $annotationsLabels.common.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    checksum/edm-applications-checkSum: {{ $checkSum  | toJson | sha256sum }}
  labels:
    cluster: {{ lower $k }}
    app: {{ lower $k }}
    {{- with $annotationsLabels.common.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ lower $k }}
  replicas: 1
  selector:
    matchLabels:
      cluster: {{ lower $k }}
      app: {{ lower $k }}
      {{- with $annotationsLabels.common.labels }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      name: {{ lower $k }}
      annotations:
        {{- with $annotationsLabels.common.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        checksum/edm-applications-checkSum: {{ $checkSum  | toJson | sha256sum }}
      labels:
        cluster: {{ lower $k }}
        app: {{ lower $k }}
        {{- with $annotationsLabels.common.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: {{ $v.securityContext.runAsUser }}
        runAsGroup: {{ $v.securityContext.runAsGroup }}
        fsGroup: {{ $v.securityContext.fsGroup }}
        fsGroupChangePolicy: {{ $v.securityContext.fsGroupChangePolicy }}
      automountServiceAccountToken: true
      serviceAccountName: {{ $basic.basic.cluster.serviceAccountName }}
      terminationGracePeriodSeconds: 0
      ### Image Pull Secret
      {{- if $basic.basic.imagePullSecretsEnabled }}
      imagePullSecrets:
        - name: {{ $basic.basic.imagePullSecretsName }}
      {{- end }}
      ### Node Affinity
      {{- with $basic.basic.cluster.node }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      ### Init container
      {{- with $initContainer }}
      {{- with index . $k }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      ### Init container - Custom
      {{- if $basic.basic.customHelm }}
      {{- with $custom.custom.initContainers }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ lower $k }}
        image: {{ $applications.applications.Cloudbeaver.image }}
        imagePullPolicy: {{ $basic.basic.imagePullPolicy }}
        env:
        - name: application_image
          value: {{ $applications.applications.Cloudbeaver.image | quote }}
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.env }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: edm-applications-config-map
            optional: false
        command: ["/bin/bash", "-c"]
        args: 
        - |
          ### Load Scripts
          . /etc/edm/functions/edm_functions.sh

          ## Main process
          cd /ext/app/cloudbeaver
          sslArguments=""
          if [[ "${DatabaseSSL}" == "require" ]]; then
             sslArguments='"sslcert": "/ext/app/protected/Certificates/db/JDBC/client-cert.cer",
                           "sslkey": "/ext/app/protected/Certificates/db/JDBC/client-key.pk8",
                           "sslrootcert": "/ext/app/protected/Certificates/db/JDBC/server-ca.cer",
                           "sslmode": "require",
                           "ssl": "true"
                          '
          fi
          
          cat <<EOF > /ext/app/cloudbeaver/conf/initial-data-sources.conf
          {
            "folders": {},
            "connections": {
                "${DatabaseName_Schema_GC}": {
                   "provider": "${database_connection_provider_cb}",
                   "driver": "${database_connection_driver}",
                   "name": "${database_connection_name_prefix} - ${DatabaseName_Schema_GC}",
                    "save-password": false,
                    "show-system-objects": false,
                    "read-only": true,
                    "template": false,
                    "configuration": {
                        "host": "${DatabaseHost_Schema_GC}",
                        "port": "${DatabasePort_Schema_GC}",
                        "database": "${database_connection_default_database}",
                        "url": "jdbc:${database_connection_provider}${DatabaseHost_Schema_GC}:${DatabasePort_Schema_GC}/${DatabaseService_Schema_GC}",
                        "type": "dev",
                        "provider-properties": {
                            "@dbeaver-show-non-default-db@": "true"
                        },
                        "properties": {
                            ${sslArguments}
                        }
                    }
                }
            }
          }
          EOF

          ## Logs
          serverLog="/${logs_home}/logs/UtilityApplications/Cloudbeaver/Cloudbeaver.log"
          mkdir -p "$(dirname "$serverLog")"
          shortDate=$(date +"%Y%m%d%H%M")
          if test -f "$serverLog"; then
             mv $serverLog $serverLog.$shortDate
          fi		 

          ## Start
          echoLog "INFO" "Cloudbeaver - $(hostname) - Image - Repository - ${application_image}" "Utility Application" "True" | tee -a /$logs_home/logs/UtilityApplications/UtilityApplications.log
          cd /ext/app/cloudbeaver
          if [[ -d "/opt/java17" ]]; then
             export JAVA_HOME=/opt/java17
             export PATH=$JAVA_HOME/bin:$PATH
          fi

          ## Run infinite
          processStarted="False"
          while true;
          do
             if [ -f "/${logs_home}/logs/Initialize/servers/restartCloudbeaver" ]; then
                pids=$(pgrep -f "cloudb" | grep -v '^1$')
                for pid in $pids; do kill -9 $pid; done
                rm -rf /${logs_home}/logs/Initialize/servers/restartCloudbeaver
                echoLog "INFO" "Cloudbeaver - $(hostname) - Stopped" "Utility Application" "True" | tee -a /$logs_home/logs/UtilityApplications/UtilityApplications.log
                processStarted="False"
                sleep 20
             fi
             if [ "$processStarted" == "False" ]; then
                ./run-server.sh > $serverLog 2>&1 &
                processStarted="True"
               echoLog "INFO" "Cloudbeaver - $(hostname) - Started" "Utility Application" "True" | tee -a /$logs_home/logs/UtilityApplications/UtilityApplications.log
             fi
             sleep 20
          done
        ports:
        - containerPort: 8978
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: {{ $v.resources.limits.cpu }}
            memory: {{ $v.resources.limits.memory }}
          requests:
            cpu: {{ $v.resources.requests.cpu }}
            memory: {{ $v.resources.requests.memory }}
        ### Volume Mounts
        {{- with $volumeMounts }}
        {{- with index . $k }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        ### Volume Mounts - Custom
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.volumeMounts }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      - name: {{ lower $k }}-keycloak-gatekeeper
        image: {{ $applications.applications.Cloudbeaver.imageGatekeeper }}
        imagePullPolicy: {{ $basic.basic.imagePullPolicy }}
        command: ["/bin/sh", "-c"]
        env:
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.env }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: edm-applications-config-map
            optional: false
        args:
        - |
          ### Load Scripts
          . /etc/edm/functions/edm_functions.sh

          ### Multiple Roles formatted
          multipleRoles={{ $v.roles | quote }}
          roles=$(echo "$multipleRoles" | sed 's/\([^,]*\)/"\1"/g' | tr -d '\n') 

          ### Configuration file
          cat <<EOF > /ext/app/keycloak_gatekeeper/oauth2-proxy.conf
            provider="keycloak-oidc"
            client_id="{{ $k }}"
            client_secret="${Keycloak_client_secret}"
            proxy_prefix="/{{ lower $k }}/oauth2"
            upstreams=["http://127.0.0.1:8978"]
            oidc_issuer_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}"
            profile_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/userinfo"
            allowed_roles=[${roles}]
            https_address="0.0.0.0:5500"
            cookie_secret="${Keycloak_cookie_secret}"
            email_domains=["*"]
            insecure_oidc_allow_unverified_email="true"
            skip_provider_button="true"
            custom_templates_dir="/ext/app/keycloak_gatekeeper"
            ssl_insecure_skip_verify="true"
            skip_oidc_discovery="true"
            login_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/auth"
            redeem_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/token"
            oidc_jwks_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/certs"
            tls_cert_file="/ext/app/protected/Certificates/ui/certificate.crt"
            tls_key_file="/ext/app/protected/Certificates/ui/private.key"
            ssl_upstream_insecure_skip_verify="true"
          EOF
          ### Start Oauth proxy
          cd /ext/app/keycloak_gatekeeper
          ./oauth2-proxy --config /ext/app/keycloak_gatekeeper/oauth2-proxy.conf
        ports:
        - containerPort: 5500
          name: http
          protocol: TCP
        ### Volume Mounts
        {{- with $volumeMounts }}
        {{- with index . $k }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        ### Volume Mounts - Custom
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.volumeMounts }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      ### Volumes
      {{- with $volumes }}
      {{- with index . $k }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      ### Volumes - Custom
      {{- if $basic.basic.customHelm }}
      {{- with $custom.custom.volumes }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
