### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
{{- $annotationsLabelsService := include "annotationsLabelsService" . | fromYaml }}
### Applications
{{- $applications := include "applications" . | fromYaml }}
### Ingresses
{{- $ingresses := include "ingresses" . | fromYaml }}
### Init container
{{- $initContainer := include "initContainer" . | fromYaml }}
### Volume Mounts
{{- $volumeMounts := include "volumeMounts" . | fromYaml }}
### Volumes
{{- $volumes := include "volumes" . | fromYaml }}
### Checksum
{{- $checkSum := include "checkSum" . | fromYaml }}
### Custom
{{- $custom := include "custom" . | fromYaml }}
###
{{- if $basic.basic.processApplications }}
###
{{- range $k, $v := $applications.applications -}}
{{- if eq "Quantworkbench" $k }}
apiVersion: v1
kind: Service
metadata:
  name: {{ lower $k }}
  annotations:
    {{- with $annotationsLabelsService.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

    ### Openshift
    {{- if eq $.Values.common.cloud "openshift" }}
    {{- if eq $.Values.ingresses.ingress.ui.ingressClassName "openshift-default" }}
    service.beta.openshift.io/serving-cert-secret-name: {{ printf "edm-openshift-%s" (lower $k) }}
    {{- end }}
    {{- end }}
  labels:
    cluster: {{ lower $k }}
    app: {{ lower $k }}
    {{- with $annotationsLabels.common.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    cluster: {{ lower $k }}
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ lower $k }}
  annotations:
    {{- with $annotationsLabels.common.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    checksum/edm-applications-checkSum: {{ $checkSum  | toJson | sha256sum }}
  labels:
    cluster: {{ lower $k }}
    app: {{ lower $k }}
    {{- with $annotationsLabels.common.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ lower $k }}
  replicas: 1
  selector:
    matchLabels:
      cluster: {{ lower $k }}
      app: {{ lower $k }}
      {{- with $annotationsLabels.common.labels }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      name: {{ lower $k }}
      annotations:
        {{- with $annotationsLabels.common.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        checksum/edm-applications-checkSum: {{ $checkSum  | toJson | sha256sum }}
      labels:
        cluster: {{ lower $k }}
        app: {{ lower $k }}
        {{- with $annotationsLabels.common.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: {{ $v.securityContext.runAsUser }}
        runAsGroup: {{ $v.securityContext.runAsGroup }}
        fsGroup: {{ $v.securityContext.fsGroup }}
        fsGroupChangePolicy: {{ $v.securityContext.fsGroupChangePolicy }}
      automountServiceAccountToken: true
      serviceAccountName: {{ $basic.basic.cluster.serviceAccountName }}
      terminationGracePeriodSeconds: 0
      ### Image Pull Secret
      {{- if $basic.basic.imagePullSecretsEnabled }}
      imagePullSecrets:
        - name: {{ $basic.basic.imagePullSecretsName }}
      {{- end }}
      ### Node Affinity
      {{- with $basic.basic.cluster.node }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      ### Init container
      {{- with $initContainer }}
      {{- with index . $k }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      ### Init container - Custom
      {{- if $basic.basic.customHelm }}
      {{- with $custom.custom.initContainers }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: quantworkbench
        image: {{ $applications.applications.Quantworkbench.image }}
        imagePullPolicy: {{ $basic.basic.imagePullPolicy }}
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "1"
        - name: NB_USER
          value: "jovyan"
        - name: NB_UID
          value: {{ $v.securityContext.runAsUser | quote }}
        - name: NB_GID
          value: {{ $v.securityContext.runAsGroup | quote }}
        - name: TEMPLATE_DIR
          value: "/ext/app/properties/rest_client.yaml.template"
        - name: CHOWN_HOME
          value: "yes"
        - name: CHOWN_EXTRA
          value: "/${mount_home}/app/quantworkbench/notebook,/home/jovyan,/opt/conda"
        - name: CHOWN_EXTRA_OPTS
          value: "-R"
        - name: application_image
          value: {{ $applications.applications.Quantworkbench.image | quote }}
        envFrom:
        - configMapRef:
            name: edm-applications-config-map
            optional: false
        command: ["/bin/bash", "-c"]
        args: 
        - |
          ### Load Scripts
          . /etc/edm/functions/edm_functions.sh

          ## Bash profile
          cd /ext/app
          . ./.bash_profile
          
          ## Check if 'local' is enabled
          if [ "$artefacts_home" == "local" ] && [ -f "/home/app/quantworkbench.tar" ]; then
             mkdir -p cd /${mount_home}/app
             cd /${mount_home}/app
             find '/home/app' -name '*.tar' -exec tar -xf {} \;
          fi        
          while true;
          do
             if [ -f "/${mount_home}/app/quantworkbench/ServerScripts/startInitQuantWorkbench.sh" ]; then
                break
             fi
             sleep 10
          done

          ## Replace properties
          restClientTemplate="/${mount_home}/app/quantworkbench/QWBSetup/properties/rest_client.yaml.template"
          sed -i 's/'%%KUBE_EXTERNAL_LB%%'/'"${KUBE_EXTERNAL_LB}"'/g' $restClientTemplate
          sed -i 's/'%%edm%%'/'"${edm_environment}"'/g' $restClientTemplate
          dos2unix /${mount_home}/app/quantworkbench/ServerScripts/startInitQuantWorkbench.sh

          ## Logs
          serverLog="/${logs_home}/logs/UtilityApplications/Quantworkbench/Quantworkbench.log"
          mkdir -p "$(dirname "$serverLog")"
          shortDate=$(date +"%Y%m%d%H%M")
          if test -f "$serverLog"; then
             mv $serverLog $serverLog.$shortDate
          fi
          
          ## Start
          echoLog "INFO" "Quantworkbench - $(hostname) - Image - Repository - ${application_image}" "Utility Application" "True" | tee -a /$logs_home/logs/UtilityApplications/UtilityApplications.log
          
          ## Run infinite
          processStarted="False"
          while true;
          do
             if [ -f "/${logs_home}/logs/Initialize/servers/restartQuantworkbench" ]; then
                pids=$(pgrep -f "quant" | grep -v '^1$')
                for pid in $pids; do kill -9 $pid; done
                rm -rf /${logs_home}/logs/Initialize/servers/restartQuantworkbench
                echoLog "INFO" "Quantworkbench - $(hostname) - Stopped" "Utility Application" "True" | tee -a /$logs_home/logs/UtilityApplications/UtilityApplications.log
                processStarted="False"
                sleep 20
             fi
             if [ "$processStarted" == "False" ]; then
                sh /${mount_home}/app/quantworkbench/ServerScripts/startInitQuantWorkbench.sh > $serverLog 2>&1 &
                processStarted="True"
                echoLog "INFO" "Quantworkbench - $(hostname) - Stopped" "Utility Application" "True" | tee -a /$logs_home/logs/UtilityApplications/UtilityApplications.log
             fi
             sleep 20
          done
        resources:
          limits:
            cpu: {{ $v.resources.limits.cpu }}
            memory: {{ $v.resources.limits.memory }}
          requests:
            cpu: {{ $v.resources.requests.cpu }}
            memory: {{ $v.resources.requests.memory }}
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        ### Volume Mounts
        {{- with $volumeMounts }}
        {{- with index . $k }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        ### Volume Mounts - Custom
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.volumeMounts }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      - name: {{ lower $k }}-keycloak-gatekeeper
        image: {{ $applications.applications.Quantworkbench.imageGatekeeper }}
        imagePullPolicy: {{ $basic.basic.imagePullPolicy }}
        command: ["/bin/sh", "-c"]      
        env:
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.env }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: edm-applications-config-map
            optional: false
        args:
        - |
          ### Load Scripts
          . /etc/edm/functions/edm_functions.sh

          ### Multiple Roles formatted
          multipleRoles={{ $v.roles | quote }}
          roles=$(echo "$multipleRoles" | sed 's/\([^,]*\)/"\1"/g' | tr -d '\n') 

          ### Configuration file
          cat <<EOF > /ext/app/keycloak_gatekeeper/oauth2-proxy.conf
            provider="keycloak-oidc"
            client_id="{{ $k }}"
            client_secret="${Keycloak_client_secret}"
            proxy_prefix="/qwb/oauth2"
            upstreams=["http://127.0.0.1:8888"]
            oidc_issuer_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}"
            profile_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/userinfo"
            allowed_roles=[${roles}]
            https_address="0.0.0.0:5000"
            cookie_secret="${Keycloak_cookie_secret}"
            email_domains=["*"]
            insecure_oidc_allow_unverified_email="true"
            skip_provider_button="true"
            custom_templates_dir="/ext/app/keycloak_gatekeeper"
            ssl_insecure_skip_verify="true"
            skip_oidc_discovery="true"
            login_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/auth"
            redeem_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/token"
            oidc_jwks_url="https://{{ $ingresses.ingresses.ui.host }}/auth/realms/{{ $basic.basic.realm }}/protocol/openid-connect/certs"
            tls_cert_file="/ext/app/protected/Certificates/ui/certificate.crt"
            tls_key_file="/ext/app/protected/Certificates/ui/private.key"
            ssl_upstream_insecure_skip_verify="true"
          EOF
          ### Start Oauth proxy
          cd /ext/app/keycloak_gatekeeper
          ./oauth2-proxy --config /ext/app/keycloak_gatekeeper/oauth2-proxy.conf
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        ### Volume Mounts
        {{- with $volumeMounts }}
        {{- with index . $k }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        ### Volume Mounts - Custom
        {{- if $basic.basic.customHelm }}
        {{- with $custom.custom.volumeMounts }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      ### Volumes
      {{- with $volumes }}
      {{- with index . $k }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      ### Volumes - Custom
      {{- if $basic.basic.customHelm }}
      {{- with $custom.custom.volumes }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
