### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabelsServiceAccount := include "annotationsLabelsServiceAccount"  . | fromYaml }}
###  
{{- if $basic.basic.externalDns }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $basic.basic.environment }}-external-dns
  {{- if eq "aws" $basic.basic.cloud.option }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.ingresses.lb.hostedZoneRoleArn }}
  {{- end }}

automountServiceAccountToken: true
{{- end }}
