### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabelsServiceAccount := include "annotationsLabelsServiceAccount"  . | fromYaml }}
###  
{{- if .Values.cluster.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $basic.basic.cluster.serviceAccountName }}
  {{- with $annotationsLabelsServiceAccount.serviceAccount}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
