### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
### Init container
{{- $initContainer := include "initContainer" . | fromYaml }}
### Volume Mounts
{{- $volumeMounts := include "volumeMounts" . | fromYaml }}
### Volumes
{{- $volumes := include "volumes" . | fromYaml }}
### Cron job
{{- $cronjobs := include "cronjobs" . | fromYaml }}
### Custom
{{- $custom := include "custom" . | fromYaml }}
###
{{- range $k, $v := $cronjobs.cronjobs -}}
{{- if and (eq $v.type "reorgDatabase") $v.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ lower $k }}
  annotations:
    {{- with $v.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $v.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ $v.schedule | quote }}
  concurrencyPolicy: Allow
  suspend: false
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ lower $k }}
          labels:
            {{- with $v.labels }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
        spec:
          securityContext:
            runAsUser: {{ $v.securityContext.runAsUser }}
            runAsGroup: {{ $v.securityContext.runAsGroup }}
            fsGroup: {{ $v.securityContext.fsGroup }}
            fsGroupChangePolicy: {{ $v.securityContext.fsGroupChangePolicy }}
          automountServiceAccountToken: true
          serviceAccountName: {{ $basic.basic.cluster.serviceAccountName }}
          ### Image Pull Secret
          {{- if $basic.basic.imagePullSecretsEnabled }}
          imagePullSecrets:
            - name: {{ $basic.basic.imagePullSecretsName }}
          {{- end }}
          ### Node Affinity
          {{- with $basic.basic.cluster.node }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          ### Init container
          {{- with $initContainer }}
          {{- with index . $k }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          ### Init container - Custom
          {{- if $basic.basic.customHelm }}
          {{- with $custom.custom.initContainers }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          containers:
          - name: {{ lower $k }}
            image: {{ $v.image }}
            imagePullPolicy: {{ $basic.basic.imagePullPolicy }}
            env:
            - name: databaseSchemas
              value: {{ $basic.basic.databaseSchemas | quote }}
            - name: databaseSchemaDetails
              value: {{ $basic.basic.databaseSchemaDetails | quote }}
            {{- if $basic.basic.customHelm }}
            {{- with $custom.custom.env }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
            envFrom:
            - configMapRef:
                name: edm-applications-config-map
                optional: false
            command: ["/bin/sh", "-c"]
            args:
            - |
              ### Load Scripts
              . /etc/edm/functions/edm_functions.sh

              ## Run infinite
              runInfinite="False"

              ## Configure Reorg Database
              rm -rf /${logs_home}/logs/CronJobs/reorgDatabase/work
              mkdir -p /${logs_home}/logs/CronJobs/reorgDatabase/work
              configureReorgDatabaseOptions={{ $.Values.jobs.cron.reorgDatabase.execute | quote }}
              configureDatabaseReorg ${configureReorgDatabaseOptions} /${logs_home}/logs/CronJobs/reorgDatabase/work /${logs_home}/logs/CronJobs/reorgDatabase/work/reorgDatabase.log

              ## Run infinite (Check)
              if [ "${runInfinite}" == "True" ]; then
                 while true;
                 do
                    tail > /dev/null
                 done
              fi
            ### Volume Mounts
            {{- with $volumeMounts }}
            {{- with index . $k }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
            ### Volume Mounts - Custom
            {{- if $basic.basic.customHelm }}
            {{- with $custom.custom.volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
          ### Volumes
          {{- with $volumes }}
          {{- with index . $k }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          ### Volumes - Custom
          {{- if $basic.basic.customHelm }}
          {{- with $custom.custom.volumes }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          restartPolicy: Never
      backoffLimit: 0
      ttlSecondsAfterFinished: 0
{{- end }}
---
{{- end }}
