### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabels := include "annotationsLabels" . | fromYaml }}
###  
{{- if .Values.cluster.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $basic.basic.cluster.role }}
  {{- with $annotationsLabels.common}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["networking","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list","update","patch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $basic.basic.cluster.role }}
  {{- with $annotationsLabels.common}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ $basic.basic.cluster.serviceAccountName }}
    namespace: {{ .Release.Namespace }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $basic.basic.cluster.role }}
{{- end }}
