### Basic, Annotations
{{- $basic := include "basic" . | fromYaml }}
{{- $annotationsLabelsIngressUi := include "annotationsLabelsIngressUi" . | fromYaml }}
### Applications
{{- $applications := include "applications" . | fromYaml }}
### Ingresses
{{- $ingresses := include "ingresses" . | fromYaml }}
###
{{- if $applications.applications }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingresses.ingresses.ui.name }}
  annotations:
    # Include ui annotations
    {{- with $ingresses.ingresses.ui.annotations}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $annotationsLabelsIngressUi.ui.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $ingresses.ingresses.ui.spec}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- if $basic.basic.cloud.ingressTls }}
  tls:
  - hosts:
    - {{ $ingresses.ingresses.ui.host }}
    secretName: {{ $ingresses.ingresses.ui.secret.name }}
  {{- end }}    
  rules:
  - http:
      paths:
      {{- range $k, $v := $applications.applications -}}
      {{- range $path := $v.contextPaths }}
      - backend:
          service:
            name: {{ lower $k }}
            port:
              number: {{ $v.port }}
        path: {{ ( printf "%s%s" $path $basic.basic.cloud.ingressPathSuffix ) }}
        pathType: ImplementationSpecific
      {{- end }}
      {{- end }}
    {{- if $basic.basic.cloud.ingressTlsHost }}
    host: {{ $ingresses.ingresses.ui.host }}
    {{- end }}
{{- end }}
